#-*-makefile-*-

BASE=../../../../
CC_add1_debug = cl6x
CC_add1_release = cl6x
CC_add1_ti_simulate = cl6x
CC_add2_debug = cl6x
CC_add2_release = cl6x
CC_add2_ti_simulate = cl6x
CFLAGS_add1_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CFLAGS_add1_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CFLAGS_add1_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CFLAGS_add2_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CFLAGS_add2_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CFLAGS_add2_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add1_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CXXFLAGS_add1_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add1_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add2_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CXXFLAGS_add2_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add2_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CXX_add1_debug = cl6x
CXX_add1_release = cl6x
CXX_add1_ti_simulate = cl6x
CXX_add2_debug = cl6x
CXX_add2_release = cl6x
CXX_add2_ti_simulate = cl6x
DEFINES_add1_debug = -DADD_THIS=1
DEFINES_add1_release = -DADD_THIS=1 -DNDEBUG=1
DEFINES_add1_ti_simulate = -DADD_THIS=1 -DNDEBUG=1
DEFINES_add2_debug = -DADD_THIS=2
DEFINES_add2_release = -DADD_THIS=2 -DNDEBUG=1
DEFINES_add2_ti_simulate = -DADD_THIS=2 -DNDEBUG=1
INCLUDES_add1_debug = -I$(BASE).
INCLUDES_add1_release = -I$(BASE).
INCLUDES_add1_ti_simulate = -I$(BASE).
INCLUDES_add2_debug = -I$(BASE).
INCLUDES_add2_release = -I$(BASE).
INCLUDES_add2_ti_simulate = -I$(BASE).
LDFLAGS_add1_debug = $(TI_LINK_COMMAND_FILE)
LDFLAGS_add1_release = $(TI_LINK_COMMAND_FILE)
LDFLAGS_add1_ti_simulate = $(TI_LINK_COMMAND_FILE)
LDFLAGS_add2_debug = $(TI_LINK_COMMAND_FILE)
LDFLAGS_add2_release = $(TI_LINK_COMMAND_FILE)
LDFLAGS_add2_ti_simulate = $(TI_LINK_COMMAND_FILE)
LDLIBS_add1_debug = -lrts6740.lib
LDLIBS_add1_release = -lrts6740.lib
LDLIBS_add1_ti_simulate = -lrts6740.lib
LDLIBS_add2_debug = -lrts6740.lib
LDLIBS_add2_release = -lrts6740.lib
LDLIBS_add2_ti_simulate = -lrts6740.lib
LD_add1_debug = lnk6x
LD_add1_release = lnk6x
LD_add1_ti_simulate = lnk6x
LD_add2_debug = lnk6x
LD_add2_release = lnk6x
LD_add2_ti_simulate = lnk6x


INPUTS_LINK_add1_debug = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.o $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.o\
                         $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.o
INPUTS_LINK_add1_release = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.o $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.o\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.o
INPUTS_LINK_add1_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.o $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.o\
                               $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.o
INPUTS_LINK_add2_debug = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.o $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.o\
                         $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.o
INPUTS_LINK_add2_release = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.o $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.o\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.o
INPUTS_LINK_add2_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.o $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.o\
                               $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.o


default: libfoo_dynamic_add1_debug.so libfoo_dynamic_add2_debug.so libfoo_dynamic_add1_release.so libfoo_dynamic_add2_release.so libfoo_dynamic_add1_ti_simulate.so libfoo_dynamic_add2_ti_simulate.so

libfoo_dynamic_add1_debug.so: $(INPUTS_LINK_add1_debug)
	$(LD_add1_debug) $(LDFLAGS_add1_debug) -o $@ $^  $(LDLIBS_add1_debug)

libfoo_dynamic_add2_debug.so: $(INPUTS_LINK_add2_debug)
	$(LD_add2_debug) $(LDFLAGS_add2_debug) -o $@ $^  $(LDLIBS_add2_debug)

libfoo_dynamic_add1_release.so: $(INPUTS_LINK_add1_release)
	$(LD_add1_release) $(LDFLAGS_add1_release) -o $@ $^  $(LDLIBS_add1_release)

libfoo_dynamic_add2_release.so: $(INPUTS_LINK_add2_release)
	$(LD_add2_release) $(LDFLAGS_add2_release) -o $@ $^  $(LDLIBS_add2_release)

libfoo_dynamic_add1_ti_simulate.so: $(INPUTS_LINK_add1_ti_simulate)
	$(LD_add1_ti_simulate) $(LDFLAGS_add1_ti_simulate) -o $@ $^  $(LDLIBS_add1_ti_simulate)

libfoo_dynamic_add2_ti_simulate.so: $(INPUTS_LINK_add2_ti_simulate)
	$(LD_add2_ti_simulate) $(LDFLAGS_add2_ti_simulate) -o $@ $^  $(LDLIBS_add2_ti_simulate)

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.o: %.c
	$(CC_add1_debug) $(CFLAGS_add1_debug) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d $(DEFINES_add1_debug) $(INCLUDES_add1_debug) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.o: %.cpp
	$(CXX_add1_debug) $(CXXFLAGS_add1_debug) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d $(DEFINES_add1_debug) $(INCLUDES_add1_debug) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.o: %.c
	$(CC_add1_release) $(CFLAGS_add1_release) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d $(DEFINES_add1_release) $(INCLUDES_add1_release) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.o: %.cpp
	$(CXX_add1_release) $(CXXFLAGS_add1_release) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d $(DEFINES_add1_release) $(INCLUDES_add1_release) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.o: %.c
	$(CC_add1_ti_simulate) $(CFLAGS_add1_ti_simulate) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d $(DEFINES_add1_ti_simulate) $(INCLUDES_add1_ti_simulate) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.o: %.cpp
	$(CXX_add1_ti_simulate) $(CXXFLAGS_add1_ti_simulate) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d $(DEFINES_add1_ti_simulate) $(INCLUDES_add1_ti_simulate) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.o: %.c
	$(CC_add2_debug) $(CFLAGS_add2_debug) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d $(DEFINES_add2_debug) $(INCLUDES_add2_debug) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.o: %.cpp
	$(CXX_add2_debug) $(CXXFLAGS_add2_debug) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d $(DEFINES_add2_debug) $(INCLUDES_add2_debug) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.o: %.c
	$(CC_add2_release) $(CFLAGS_add2_release) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d $(DEFINES_add2_release) $(INCLUDES_add2_release) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.o: %.cpp
	$(CXX_add2_release) $(CXXFLAGS_add2_release) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d $(DEFINES_add2_release) $(INCLUDES_add2_release) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.o: %.c
	$(CC_add2_ti_simulate) $(CFLAGS_add2_ti_simulate) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d $(DEFINES_add2_ti_simulate) $(INCLUDES_add2_ti_simulate) --output_file=$@ $<

%.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.o: %.cpp
	$(CXX_add2_ti_simulate) $(CXXFLAGS_add2_ti_simulate) --preproc_dependency=$*.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d $(DEFINES_add2_ti_simulate) $(INCLUDES_add2_ti_simulate) --output_file=$@ $<

CLEAN_COMPILE_add1_debug = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d
CLEAN_COMPILE_add1_release = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d\
                             $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d
CLEAN_COMPILE_add1_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d\
                                 $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d
CLEAN_COMPILE_add2_debug = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d
CLEAN_COMPILE_add2_release = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d\
                             $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d
CLEAN_COMPILE_add2_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d\
                                 $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d

cleandeps:
	$(RM) $(CLEAN_COMPILE_add1_debug)
	$(RM) $(CLEAN_COMPILE_add1_release)
	$(RM) $(CLEAN_COMPILE_add1_ti_simulate)
	$(RM) $(CLEAN_COMPILE_add2_debug)
	$(RM) $(CLEAN_COMPILE_add2_release)
	$(RM) $(CLEAN_COMPILE_add2_ti_simulate)

clean: cleanself

cleanself:
	$(RM) $(CLEAN_COMPILE_add1_debug)
	$(RM) $(CLEAN_COMPILE_add1_release)
	$(RM) $(CLEAN_COMPILE_add1_ti_simulate)
	$(RM) $(CLEAN_COMPILE_add2_debug)
	$(RM) $(CLEAN_COMPILE_add2_release)
	$(RM) $(CLEAN_COMPILE_add2_ti_simulate)
	$(RM) $(INPUTS_LINK_add1_debug)
	$(RM) $(INPUTS_LINK_add2_debug)
	$(RM) $(INPUTS_LINK_add1_release)
	$(RM) $(INPUTS_LINK_add2_release)
	$(RM) $(INPUTS_LINK_add1_ti_simulate)
	$(RM) $(INPUTS_LINK_add2_ti_simulate)
	$(RM) libfoo_dynamic_add1_debug.so
	$(RM) libfoo_dynamic_add2_debug.so
	$(RM) libfoo_dynamic_add1_release.so
	$(RM) libfoo_dynamic_add2_release.so
	$(RM) libfoo_dynamic_add1_ti_simulate.so
	$(RM) libfoo_dynamic_add2_ti_simulate.so

.PHONY: default FORCE clean cleandeps cleanself help

FORCE:

help:
	@echo "This makefile has the following targets:"
	@echo " libfoo_dynamic_add1_debug.so"
	@echo " libfoo_dynamic_add2_debug.so"
	@echo " libfoo_dynamic_add1_release.so"
	@echo " libfoo_dynamic_add2_release.so"
	@echo " libfoo_dynamic_add1_ti_simulate.so"
	@echo " libfoo_dynamic_add2_ti_simulate.so"
	@echo " default"
	@echo " clean"
	@echo " cleandeps"
	@echo " help"

include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_dynamic_tisim_coffabi_c674_ccs_add2_ti_simulate.d)


