#-*-makefile-*-

BASE=../../../../../../../../../
CCDEP_a0_c0_debug = $(CC)
CCDEP_a0_c0_release = $(CC)
CCDEP_a0_c1_debug = $(CC)
CCDEP_a0_c1_release = $(CC)
CCDEP_a1_c0_debug = $(CC)
CCDEP_a1_c0_release = $(CC)
CCDEP_a1_c1_debug = $(CC)
CCDEP_a1_c1_release = $(CC)
CC_a0_c0_debug = $(CC)
CC_a0_c0_release = $(CC)
CC_a0_c1_debug = $(CC)
CC_a0_c1_release = $(CC)
CC_a1_c0_debug = $(CC)
CC_a1_c0_release = $(CC)
CC_a1_c1_debug = $(CC)
CC_a1_c1_release = $(CC)
CFLAGS_a0_c0_debug = -g -ggdb3 -O0 -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
CFLAGS_a0_c0_release = -O3 -funroll-loops -ftree-vectorize -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
CFLAGS_a0_c1_debug = -g -ggdb3 -O0 -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
CFLAGS_a0_c1_release = -O3 -funroll-loops -ftree-vectorize -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
CFLAGS_a1_c0_debug = -g -ggdb3 -O0 -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
CFLAGS_a1_c0_release = -O3 -funroll-loops -ftree-vectorize -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
CFLAGS_a1_c1_debug = -g -ggdb3 -O0 -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
CFLAGS_a1_c1_release = -O3 -funroll-loops -ftree-vectorize -m64 -c -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -pedantic -std=gnu99 -Wdeclaration-after-statement -Wvla
DEFINES_a0_c0_debug = -DPROJECT_A=1
DEFINES_a0_c0_release = -DNDEBUG=1 -DPROJECT_A=1
DEFINES_a0_c1_debug = -DPROJECT_A=1
DEFINES_a0_c1_release = -DNDEBUG=1 -DPROJECT_A=1
DEFINES_a1_c0_debug = -DPROJECT_A=1
DEFINES_a1_c0_release = -DNDEBUG=1 -DPROJECT_A=1
DEFINES_a1_c1_debug = -DPROJECT_A=1
DEFINES_a1_c1_release = -DNDEBUG=1 -DPROJECT_A=1
INCLUDES_a0_c0_debug = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
INCLUDES_a0_c0_release = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
INCLUDES_a0_c1_debug = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
INCLUDES_a0_c1_release = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
INCLUDES_a1_c0_debug = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
INCLUDES_a1_c0_release = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
INCLUDES_a1_c1_debug = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
INCLUDES_a1_c1_release = -I$(BASE)mbuild/src/test/testcases/backend/input/project_a
LDFLAGS_a0_c0_debug = -rdynamic -m64
LDFLAGS_a0_c0_release = -O2 -m64
LDFLAGS_a0_c1_debug = -rdynamic -m64
LDFLAGS_a0_c1_release = -O2 -m64
LDFLAGS_a1_c0_debug = -rdynamic -m64
LDFLAGS_a1_c0_release = -O2 -m64
LDFLAGS_a1_c1_debug = -rdynamic -m64
LDFLAGS_a1_c1_release = -O2 -m64
LD_a0_c0_debug = gcc
LD_a0_c0_release = gcc
LD_a0_c1_debug = gcc
LD_a0_c1_release = gcc
LD_a1_c0_debug = gcc
LD_a1_c0_release = gcc
LD_a1_c1_debug = gcc
LD_a1_c1_release = gcc

COMMON_FILES = $(BASE)mbuild/src/test/testcases/backend/input/project_a/file

INPUTS_COMMON_LINK_a0_c0_debug = $(addsuffix .project_a_osx_amd64_gnu_a0_c0_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_a0_c0_release = $(addsuffix .project_a_osx_amd64_gnu_a0_c0_release.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_a0_c1_debug = $(addsuffix .project_a_osx_amd64_gnu_a0_c1_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_a0_c1_release = $(addsuffix .project_a_osx_amd64_gnu_a0_c1_release.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_a1_c0_debug = $(addsuffix .project_a_osx_amd64_gnu_a1_c0_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_a1_c0_release = $(addsuffix .project_a_osx_amd64_gnu_a1_c0_release.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_a1_c1_debug = $(addsuffix .project_a_osx_amd64_gnu_a1_c1_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_a1_c1_release = $(addsuffix .project_a_osx_amd64_gnu_a1_c1_release.o,$(COMMON_FILES))

DEP_PROJ_LINK_a0_c0_debug = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c0_debug.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c0_debug.a
DEP_PROJ_LINK_a0_c0_release = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c0_release.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c0_release.a
DEP_PROJ_LINK_a0_c1_debug = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c1_debug.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c1_debug.a
DEP_PROJ_LINK_a0_c1_release = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c1_release.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c1_release.a
DEP_PROJ_LINK_a1_c0_debug = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c0_debug.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c0_debug.a
DEP_PROJ_LINK_a1_c0_release = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c0_release.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c0_release.a
DEP_PROJ_LINK_a1_c1_debug = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c1_debug.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c1_debug.a
DEP_PROJ_LINK_a1_c1_release = $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu/project_b_c1_release.a $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu/project_c_c1_release.a

default: project_a_a0_c0_debug project_a_a0_c1_debug project_a_a1_c0_debug project_a_a1_c1_debug project_a_a0_c0_release project_a_a0_c1_release project_a_a1_c0_release project_a_a1_c1_release

project_a_a0_c0_debug: $(INPUTS_COMMON_LINK_a0_c0_debug) $(DEP_PROJ_LINK_a0_c0_debug)
	$(LD_a0_c0_debug) $(LDFLAGS_a0_c0_debug) -o $@ $+ 

project_a_a0_c1_debug: $(INPUTS_COMMON_LINK_a0_c1_debug) $(DEP_PROJ_LINK_a0_c1_debug)
	$(LD_a0_c1_debug) $(LDFLAGS_a0_c1_debug) -o $@ $+ 

project_a_a1_c0_debug: $(INPUTS_COMMON_LINK_a1_c0_debug) $(DEP_PROJ_LINK_a1_c0_debug)
	$(LD_a1_c0_debug) $(LDFLAGS_a1_c0_debug) -o $@ $+ 

project_a_a1_c1_debug: $(INPUTS_COMMON_LINK_a1_c1_debug) $(DEP_PROJ_LINK_a1_c1_debug)
	$(LD_a1_c1_debug) $(LDFLAGS_a1_c1_debug) -o $@ $+ 

project_a_a0_c0_release: $(INPUTS_COMMON_LINK_a0_c0_release) $(DEP_PROJ_LINK_a0_c0_release)
	$(LD_a0_c0_release) $(LDFLAGS_a0_c0_release) -o $@ $+ 

project_a_a0_c1_release: $(INPUTS_COMMON_LINK_a0_c1_release) $(DEP_PROJ_LINK_a0_c1_release)
	$(LD_a0_c1_release) $(LDFLAGS_a0_c1_release) -o $@ $+ 

project_a_a1_c0_release: $(INPUTS_COMMON_LINK_a1_c0_release) $(DEP_PROJ_LINK_a1_c0_release)
	$(LD_a1_c0_release) $(LDFLAGS_a1_c0_release) -o $@ $+ 

project_a_a1_c1_release: $(INPUTS_COMMON_LINK_a1_c1_release) $(DEP_PROJ_LINK_a1_c1_release)
	$(LD_a1_c1_release) $(LDFLAGS_a1_c1_release) -o $@ $+ 

%.project_a_osx_amd64_gnu_a0_c0_debug.o: %.c
	$(CCDEP_a0_c0_debug) -MM $(DEFINES_a0_c0_debug) $(INCLUDES_a0_c0_debug) -MT $@ -o $*.project_a_osx_amd64_gnu_a0_c0_debug.d $<
	$(CC_a0_c0_debug) $(CFLAGS_a0_c0_debug) $(DEFINES_a0_c0_debug) $(INCLUDES_a0_c0_debug) -o $@ $<

%.project_a_osx_amd64_gnu_a0_c0_release.o: %.c
	$(CCDEP_a0_c0_release) -MM $(DEFINES_a0_c0_release) $(INCLUDES_a0_c0_release) -MT $@ -o $*.project_a_osx_amd64_gnu_a0_c0_release.d $<
	$(CC_a0_c0_release) $(CFLAGS_a0_c0_release) $(DEFINES_a0_c0_release) $(INCLUDES_a0_c0_release) -o $@ $<

%.project_a_osx_amd64_gnu_a0_c1_debug.o: %.c
	$(CCDEP_a0_c1_debug) -MM $(DEFINES_a0_c1_debug) $(INCLUDES_a0_c1_debug) -MT $@ -o $*.project_a_osx_amd64_gnu_a0_c1_debug.d $<
	$(CC_a0_c1_debug) $(CFLAGS_a0_c1_debug) $(DEFINES_a0_c1_debug) $(INCLUDES_a0_c1_debug) -o $@ $<

%.project_a_osx_amd64_gnu_a0_c1_release.o: %.c
	$(CCDEP_a0_c1_release) -MM $(DEFINES_a0_c1_release) $(INCLUDES_a0_c1_release) -MT $@ -o $*.project_a_osx_amd64_gnu_a0_c1_release.d $<
	$(CC_a0_c1_release) $(CFLAGS_a0_c1_release) $(DEFINES_a0_c1_release) $(INCLUDES_a0_c1_release) -o $@ $<

%.project_a_osx_amd64_gnu_a1_c0_debug.o: %.c
	$(CCDEP_a1_c0_debug) -MM $(DEFINES_a1_c0_debug) $(INCLUDES_a1_c0_debug) -MT $@ -o $*.project_a_osx_amd64_gnu_a1_c0_debug.d $<
	$(CC_a1_c0_debug) $(CFLAGS_a1_c0_debug) $(DEFINES_a1_c0_debug) $(INCLUDES_a1_c0_debug) -o $@ $<

%.project_a_osx_amd64_gnu_a1_c0_release.o: %.c
	$(CCDEP_a1_c0_release) -MM $(DEFINES_a1_c0_release) $(INCLUDES_a1_c0_release) -MT $@ -o $*.project_a_osx_amd64_gnu_a1_c0_release.d $<
	$(CC_a1_c0_release) $(CFLAGS_a1_c0_release) $(DEFINES_a1_c0_release) $(INCLUDES_a1_c0_release) -o $@ $<

%.project_a_osx_amd64_gnu_a1_c1_debug.o: %.c
	$(CCDEP_a1_c1_debug) -MM $(DEFINES_a1_c1_debug) $(INCLUDES_a1_c1_debug) -MT $@ -o $*.project_a_osx_amd64_gnu_a1_c1_debug.d $<
	$(CC_a1_c1_debug) $(CFLAGS_a1_c1_debug) $(DEFINES_a1_c1_debug) $(INCLUDES_a1_c1_debug) -o $@ $<

%.project_a_osx_amd64_gnu_a1_c1_release.o: %.c
	$(CCDEP_a1_c1_release) -MM $(DEFINES_a1_c1_release) $(INCLUDES_a1_c1_release) -MT $@ -o $*.project_a_osx_amd64_gnu_a1_c1_release.d $<
	$(CC_a1_c1_release) $(CFLAGS_a1_c1_release) $(DEFINES_a1_c1_release) $(INCLUDES_a1_c1_release) -o $@ $<

CLEAN_COMMON_COMPILE_a0_c0_debug = $(addsuffix .project_a_osx_amd64_gnu_a0_c0_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_a0_c0_release = $(addsuffix .project_a_osx_amd64_gnu_a0_c0_release.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_a0_c1_debug = $(addsuffix .project_a_osx_amd64_gnu_a0_c1_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_a0_c1_release = $(addsuffix .project_a_osx_amd64_gnu_a0_c1_release.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_a1_c0_debug = $(addsuffix .project_a_osx_amd64_gnu_a1_c0_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_a1_c0_release = $(addsuffix .project_a_osx_amd64_gnu_a1_c0_release.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_a1_c1_debug = $(addsuffix .project_a_osx_amd64_gnu_a1_c1_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_a1_c1_release = $(addsuffix .project_a_osx_amd64_gnu_a1_c1_release.d,$(COMMON_FILES))

cleandeps:
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c0_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c0_release)
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c1_release)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c0_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c0_release)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c1_release)

clean: cleanself
	$(MAKE) -C $(BASE)mbuild/src/test/testcases/backend/input/project_b/project_b/osx_amd64_gnu cleanself
	$(MAKE) -C $(BASE)mbuild/src/test/testcases/backend/input/project_c/project_c/osx_amd64_gnu cleanself

cleanself:
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c0_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c0_release)
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a0_c1_release)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c0_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c0_release)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_a1_c1_release)
	$(RM) $(INPUTS_COMMON_LINK_a0_c0_debug)
	$(RM) $(INPUTS_COMMON_LINK_a0_c1_debug)
	$(RM) $(INPUTS_COMMON_LINK_a1_c0_debug)
	$(RM) $(INPUTS_COMMON_LINK_a1_c1_debug)
	$(RM) $(INPUTS_COMMON_LINK_a0_c0_release)
	$(RM) $(INPUTS_COMMON_LINK_a0_c1_release)
	$(RM) $(INPUTS_COMMON_LINK_a1_c0_release)
	$(RM) $(INPUTS_COMMON_LINK_a1_c1_release)
	$(RM) project_a_a0_c0_debug
	$(RM) project_a_a0_c1_debug
	$(RM) project_a_a1_c0_debug
	$(RM) project_a_a1_c1_debug
	$(RM) project_a_a0_c0_release
	$(RM) project_a_a0_c1_release
	$(RM) project_a_a1_c0_release
	$(RM) project_a_a1_c1_release

.PHONY: default FORCE clean cleandeps cleanself help

FORCE:

help:
	@echo "This makefile has the following targets:"
	@echo " project_a_a0_c0_debug"
	@echo " project_a_a0_c1_debug"
	@echo " project_a_a1_c0_debug"
	@echo " project_a_a1_c1_debug"
	@echo " project_a_a0_c0_release"
	@echo " project_a_a0_c1_release"
	@echo " project_a_a1_c0_release"
	@echo " project_a_a1_c1_release"
	@echo " default"
	@echo " clean"
	@echo " cleandeps"
	@echo " help"

include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a0_c0_debug.d)
include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a0_c0_release.d)
include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a0_c1_debug.d)
include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a0_c1_release.d)
include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a1_c0_debug.d)
include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a1_c0_release.d)
include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a1_c1_debug.d)
include $(wildcard $(BASE)mbuild/src/test/testcases/backend/input/project_a/file.project_a_osx_amd64_gnu_a1_c1_release.d)

%.a: FORCE
	$(MAKE) -C $(@D) $(@F)


