#-*-makefile-*-

BASE=../../../../
ARFLAGS_add1_debug = -ru
ARFLAGS_add1_release = -ru
ARFLAGS_add1_ti_simulate = -ru
ARFLAGS_add2_debug = -ru
ARFLAGS_add2_release = -ru
ARFLAGS_add2_ti_simulate = -ru
AR_add1_debug = ar6x
AR_add1_release = ar6x
AR_add1_ti_simulate = ar6x
AR_add2_debug = ar6x
AR_add2_release = ar6x
AR_add2_ti_simulate = ar6x
CC_add1_debug = c6runapp-cc
CC_add1_release = c6runapp-cc
CC_add1_ti_simulate = c6runapp-cc
CC_add2_debug = c6runapp-cc
CC_add2_release = c6runapp-cc
CC_add2_ti_simulate = c6runapp-cc
CFLAGS_add1_debug = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -g --preproc_with_compile
CFLAGS_add1_release = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -O3 -pm -mf --preproc_with_compile
CFLAGS_add1_ti_simulate = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CFLAGS_add2_debug = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -g --preproc_with_compile
CFLAGS_add2_release = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -O3 -pm -mf --preproc_with_compile
CFLAGS_add2_ti_simulate = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add1_debug = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -g --preproc_with_compile
CXXFLAGS_add1_release = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add1_ti_simulate = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add2_debug = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -g --preproc_with_compile
CXXFLAGS_add2_release = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p -O3 -pm -mf --preproc_with_compile
CXXFLAGS_add2_ti_simulate = -c --gcc -on2 -pden -pdv --abi=eabi --strip_coff_underscore -mv67p --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CXX_add1_debug = c6runapp-cc
CXX_add1_release = c6runapp-cc
CXX_add1_ti_simulate = c6runapp-cc
CXX_add2_debug = c6runapp-cc
CXX_add2_release = c6runapp-cc
CXX_add2_ti_simulate = c6runapp-cc
DEFINES_add1_debug = -DADD_THIS=1
DEFINES_add1_release = -DADD_THIS=1 -DNDEBUG=1
DEFINES_add1_ti_simulate = -DADD_THIS=1 -DNDEBUG=1
DEFINES_add2_debug = -DADD_THIS=2
DEFINES_add2_release = -DADD_THIS=2 -DNDEBUG=1
DEFINES_add2_ti_simulate = -DADD_THIS=2 -DNDEBUG=1
INCLUDES_add1_debug = -I$(BASE).
INCLUDES_add1_release = -I$(BASE).
INCLUDES_add1_ti_simulate = -I$(BASE).
INCLUDES_add2_debug = -I$(BASE).
INCLUDES_add2_release = -I$(BASE).
INCLUDES_add2_ti_simulate = -I$(BASE).


INPUTS_ARCHIVE_add1_debug = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.o\
                            $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.o
INPUTS_ARCHIVE_add1_release = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.o\
                              $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.o
INPUTS_ARCHIVE_add1_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.o\
                                  $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.o\
                                  $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.o
INPUTS_ARCHIVE_add2_debug = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.o\
                            $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.o
INPUTS_ARCHIVE_add2_release = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.o\
                              $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.o
INPUTS_ARCHIVE_add2_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.o\
                                  $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.o\
                                  $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.o


default: libfoo_static_add1_debug.lib libfoo_static_add2_debug.lib libfoo_static_add1_release.lib libfoo_static_add2_release.lib libfoo_static_add1_ti_simulate.lib libfoo_static_add2_ti_simulate.lib

libfoo_static_add1_debug.lib: $(INPUTS_ARCHIVE_add1_debug)
	$(AR_add1_debug) $(ARFLAGS_add1_debug)   $@ $^

libfoo_static_add2_debug.lib: $(INPUTS_ARCHIVE_add2_debug)
	$(AR_add2_debug) $(ARFLAGS_add2_debug)   $@ $^

libfoo_static_add1_release.lib: $(INPUTS_ARCHIVE_add1_release)
	$(AR_add1_release) $(ARFLAGS_add1_release)   $@ $^

libfoo_static_add2_release.lib: $(INPUTS_ARCHIVE_add2_release)
	$(AR_add2_release) $(ARFLAGS_add2_release)   $@ $^

libfoo_static_add1_ti_simulate.lib: $(INPUTS_ARCHIVE_add1_ti_simulate)
	$(AR_add1_ti_simulate) $(ARFLAGS_add1_ti_simulate)   $@ $^

libfoo_static_add2_ti_simulate.lib: $(INPUTS_ARCHIVE_add2_ti_simulate)
	$(AR_add2_ti_simulate) $(ARFLAGS_add2_ti_simulate)   $@ $^

%.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.o: %.c
	$(CC_add1_debug) $(CFLAGS_add1_debug) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d $(DEFINES_add1_debug) $(INCLUDES_add1_debug) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.o: %.cpp
	$(CXX_add1_debug) $(CXXFLAGS_add1_debug) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d $(DEFINES_add1_debug) $(INCLUDES_add1_debug) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.o: %.c
	$(CC_add1_release) $(CFLAGS_add1_release) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d $(DEFINES_add1_release) $(INCLUDES_add1_release) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.o: %.cpp
	$(CXX_add1_release) $(CXXFLAGS_add1_release) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d $(DEFINES_add1_release) $(INCLUDES_add1_release) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.o: %.c
	$(CC_add1_ti_simulate) $(CFLAGS_add1_ti_simulate) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d $(DEFINES_add1_ti_simulate) $(INCLUDES_add1_ti_simulate) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.o: %.cpp
	$(CXX_add1_ti_simulate) $(CXXFLAGS_add1_ti_simulate) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d $(DEFINES_add1_ti_simulate) $(INCLUDES_add1_ti_simulate) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.o: %.c
	$(CC_add2_debug) $(CFLAGS_add2_debug) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d $(DEFINES_add2_debug) $(INCLUDES_add2_debug) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.o: %.cpp
	$(CXX_add2_debug) $(CXXFLAGS_add2_debug) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d $(DEFINES_add2_debug) $(INCLUDES_add2_debug) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.o: %.c
	$(CC_add2_release) $(CFLAGS_add2_release) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d $(DEFINES_add2_release) $(INCLUDES_add2_release) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.o: %.cpp
	$(CXX_add2_release) $(CXXFLAGS_add2_release) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d $(DEFINES_add2_release) $(INCLUDES_add2_release) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.o: %.c
	$(CC_add2_ti_simulate) $(CFLAGS_add2_ti_simulate) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d $(DEFINES_add2_ti_simulate) $(INCLUDES_add2_ti_simulate) -o$@ $<

%.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.o: %.cpp
	$(CXX_add2_ti_simulate) $(CXXFLAGS_add2_ti_simulate) --preproc_dependency=$*.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d $(DEFINES_add2_ti_simulate) $(INCLUDES_add2_ti_simulate) -o$@ $<

CLEAN_COMPILE_add1_debug = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d
CLEAN_COMPILE_add1_release = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d\
                             $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d
CLEAN_COMPILE_add1_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d\
                                 $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d
CLEAN_COMPILE_add2_debug = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d
CLEAN_COMPILE_add2_release = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d\
                             $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d
CLEAN_COMPILE_add2_ti_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d\
                                 $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d

cleandeps:
	$(RM) $(CLEAN_COMPILE_add1_debug)
	$(RM) $(CLEAN_COMPILE_add1_release)
	$(RM) $(CLEAN_COMPILE_add1_ti_simulate)
	$(RM) $(CLEAN_COMPILE_add2_debug)
	$(RM) $(CLEAN_COMPILE_add2_release)
	$(RM) $(CLEAN_COMPILE_add2_ti_simulate)

clean: cleanself

cleanself:
	$(RM) $(CLEAN_COMPILE_add1_debug)
	$(RM) $(CLEAN_COMPILE_add1_release)
	$(RM) $(CLEAN_COMPILE_add1_ti_simulate)
	$(RM) $(CLEAN_COMPILE_add2_debug)
	$(RM) $(CLEAN_COMPILE_add2_release)
	$(RM) $(CLEAN_COMPILE_add2_ti_simulate)
	$(RM) $(INPUTS_ARCHIVE_add1_debug)
	$(RM) $(INPUTS_ARCHIVE_add2_debug)
	$(RM) $(INPUTS_ARCHIVE_add1_release)
	$(RM) $(INPUTS_ARCHIVE_add2_release)
	$(RM) $(INPUTS_ARCHIVE_add1_ti_simulate)
	$(RM) $(INPUTS_ARCHIVE_add2_ti_simulate)
	$(RM) libfoo_static_add1_debug.lib
	$(RM) libfoo_static_add2_debug.lib
	$(RM) libfoo_static_add1_release.lib
	$(RM) libfoo_static_add2_release.lib
	$(RM) libfoo_static_add1_ti_simulate.lib
	$(RM) libfoo_static_add2_ti_simulate.lib

.PHONY: default FORCE clean cleandeps cleanself help

FORCE:

help:
	@echo "This makefile has the following targets:"
	@echo " libfoo_static_add1_debug.lib"
	@echo " libfoo_static_add2_debug.lib"
	@echo " libfoo_static_add1_release.lib"
	@echo " libfoo_static_add2_release.lib"
	@echo " libfoo_static_add1_ti_simulate.lib"
	@echo " libfoo_static_add2_ti_simulate.lib"
	@echo " default"
	@echo " clean"
	@echo " cleandeps"
	@echo " help"

include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_tisim_eabi_c67plus_c6run_add2_ti_simulate.d)


