#-*-makefile-*-

BASE=../../../../

ifndef TI_LINK_COMMAND_FILE
$(error "$${TI_LINK_COMMAND_FILE} is not defined. The file is used to pass options, arguments and memory layout of your target platform to linker.")
endif
CC_lower_add1_debug = c6runapp-cc
CC_lower_add1_release = c6runapp-cc
CC_lower_add1_ti_simulate = c6runapp-cc
CC_lower_add2_debug = c6runapp-cc
CC_lower_add2_release = c6runapp-cc
CC_lower_add2_ti_simulate = c6runapp-cc
CC_upper_add1_debug = c6runapp-cc
CC_upper_add1_release = c6runapp-cc
CC_upper_add1_ti_simulate = c6runapp-cc
CC_upper_add2_debug = c6runapp-cc
CC_upper_add2_release = c6runapp-cc
CC_upper_add2_ti_simulate = c6runapp-cc
CFLAGS_lower_add1_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CFLAGS_lower_add1_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CFLAGS_lower_add1_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CFLAGS_lower_add2_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CFLAGS_lower_add2_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CFLAGS_lower_add2_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CFLAGS_upper_add1_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CFLAGS_upper_add1_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CFLAGS_upper_add1_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
CFLAGS_upper_add2_debug = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -g --preproc_with_compile
CFLAGS_upper_add2_release = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 -O3 -pm -mf --preproc_with_compile
CFLAGS_upper_add2_ti_simulate = -c --gcc -on2 -pden -pdv --abi=coffabi -mv6740 --optimize_with_debug -g -O3 -pm -mf --preproc_with_compile
DEFINES_lower_add1_debug = -DADD_THIS=1 -DGET_NAME_TRANSFORM=tolower
DEFINES_lower_add1_release = -DADD_THIS=1 -DGET_NAME_TRANSFORM=tolower -DNDEBUG=1
DEFINES_lower_add1_ti_simulate = -DADD_THIS=1 -DGET_NAME_TRANSFORM=tolower -DNDEBUG=1
DEFINES_lower_add2_debug = -DADD_THIS=2 -DGET_NAME_TRANSFORM=tolower
DEFINES_lower_add2_release = -DADD_THIS=2 -DGET_NAME_TRANSFORM=tolower -DNDEBUG=1
DEFINES_lower_add2_ti_simulate = -DADD_THIS=2 -DGET_NAME_TRANSFORM=tolower -DNDEBUG=1
DEFINES_upper_add1_debug = -DADD_THIS=1 -DGET_NAME_TRANSFORM=toupper
DEFINES_upper_add1_release = -DADD_THIS=1 -DGET_NAME_TRANSFORM=toupper -DNDEBUG=1
DEFINES_upper_add1_ti_simulate = -DADD_THIS=1 -DGET_NAME_TRANSFORM=toupper -DNDEBUG=1
DEFINES_upper_add2_debug = -DADD_THIS=2 -DGET_NAME_TRANSFORM=toupper
DEFINES_upper_add2_release = -DADD_THIS=2 -DGET_NAME_TRANSFORM=toupper -DNDEBUG=1
DEFINES_upper_add2_ti_simulate = -DADD_THIS=2 -DGET_NAME_TRANSFORM=toupper -DNDEBUG=1
INCLUDES_lower_add1_debug = -I$(BASE).
INCLUDES_lower_add1_release = -I$(BASE).
INCLUDES_lower_add1_ti_simulate = -I$(BASE).
INCLUDES_lower_add2_debug = -I$(BASE).
INCLUDES_lower_add2_release = -I$(BASE).
INCLUDES_lower_add2_ti_simulate = -I$(BASE).
INCLUDES_upper_add1_debug = -I$(BASE).
INCLUDES_upper_add1_release = -I$(BASE).
INCLUDES_upper_add1_ti_simulate = -I$(BASE).
INCLUDES_upper_add2_debug = -I$(BASE).
INCLUDES_upper_add2_release = -I$(BASE).
INCLUDES_upper_add2_ti_simulate = -I$(BASE).
LDFLAGS_lower_add1_debug = $(TI_LINK_COMMAND_FILE)
LDFLAGS_lower_add1_release = $(TI_LINK_COMMAND_FILE)
LDFLAGS_lower_add1_ti_simulate = $(TI_LINK_COMMAND_FILE)
LDFLAGS_lower_add2_debug = $(TI_LINK_COMMAND_FILE)
LDFLAGS_lower_add2_release = $(TI_LINK_COMMAND_FILE)
LDFLAGS_lower_add2_ti_simulate = $(TI_LINK_COMMAND_FILE)
LDFLAGS_upper_add1_debug = $(TI_LINK_COMMAND_FILE)
LDFLAGS_upper_add1_release = $(TI_LINK_COMMAND_FILE)
LDFLAGS_upper_add1_ti_simulate = $(TI_LINK_COMMAND_FILE)
LDFLAGS_upper_add2_debug = $(TI_LINK_COMMAND_FILE)
LDFLAGS_upper_add2_release = $(TI_LINK_COMMAND_FILE)
LDFLAGS_upper_add2_ti_simulate = $(TI_LINK_COMMAND_FILE)
LD_lower_add1_debug = c6runapp-cc
LD_lower_add1_release = c6runapp-cc
LD_lower_add1_ti_simulate = c6runapp-cc
LD_lower_add2_debug = c6runapp-cc
LD_lower_add2_release = c6runapp-cc
LD_lower_add2_ti_simulate = c6runapp-cc
LD_upper_add1_debug = c6runapp-cc
LD_upper_add1_release = c6runapp-cc
LD_upper_add1_ti_simulate = c6runapp-cc
LD_upper_add2_debug = c6runapp-cc
LD_upper_add2_release = c6runapp-cc
LD_upper_add2_ti_simulate = c6runapp-cc

COMMON_FILES = $(BASE)example-2/frontend/main $(BASE)example-2/src/get_name/get_name $(BASE)example-2/src/get_name/get_name_raw

INPUTS_COMMON_LINK_lower_add1_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add1_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_lower_add1_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add1_release.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_lower_add1_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add1_ti_simulate.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_lower_add2_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add2_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_lower_add2_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add2_release.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_lower_add2_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add2_ti_simulate.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_upper_add1_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add1_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_upper_add1_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add1_release.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_upper_add1_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add1_ti_simulate.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_upper_add2_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add2_debug.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_upper_add2_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add2_release.o,$(COMMON_FILES))
INPUTS_COMMON_LINK_upper_add2_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add2_ti_simulate.o,$(COMMON_FILES))

DEP_PROJ_LINK_lower_add1_debug = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add1_debug.lib
DEP_PROJ_LINK_lower_add1_release = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add1_release.lib
DEP_PROJ_LINK_lower_add1_ti_simulate = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add1_ti_simulate.lib
DEP_PROJ_LINK_lower_add2_debug = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add2_debug.lib
DEP_PROJ_LINK_lower_add2_release = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add2_release.lib
DEP_PROJ_LINK_lower_add2_ti_simulate = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add2_ti_simulate.lib
DEP_PROJ_LINK_upper_add1_debug = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add1_debug.lib
DEP_PROJ_LINK_upper_add1_release = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add1_release.lib
DEP_PROJ_LINK_upper_add1_ti_simulate = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add1_ti_simulate.lib
DEP_PROJ_LINK_upper_add2_debug = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add2_debug.lib
DEP_PROJ_LINK_upper_add2_release = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add2_release.lib
DEP_PROJ_LINK_upper_add2_ti_simulate = $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run/libfoo_static_add2_ti_simulate.lib

default: get_name_static_lower_add1_debug.axf get_name_static_lower_add2_debug.axf get_name_static_upper_add1_debug.axf get_name_static_upper_add2_debug.axf get_name_static_lower_add1_release.axf get_name_static_lower_add2_release.axf get_name_static_upper_add1_release.axf get_name_static_upper_add2_release.axf get_name_static_lower_add1_ti_simulate.axf get_name_static_lower_add2_ti_simulate.axf get_name_static_upper_add1_ti_simulate.axf get_name_static_upper_add2_ti_simulate.axf

get_name_static_lower_add1_debug.axf: $(INPUTS_COMMON_LINK_lower_add1_debug) $(DEP_PROJ_LINK_lower_add1_debug)
	$(LD_lower_add1_debug) $(LDFLAGS_lower_add1_debug) -o $@ $^  

get_name_static_lower_add2_debug.axf: $(INPUTS_COMMON_LINK_lower_add2_debug) $(DEP_PROJ_LINK_lower_add2_debug)
	$(LD_lower_add2_debug) $(LDFLAGS_lower_add2_debug) -o $@ $^  

get_name_static_upper_add1_debug.axf: $(INPUTS_COMMON_LINK_upper_add1_debug) $(DEP_PROJ_LINK_upper_add1_debug)
	$(LD_upper_add1_debug) $(LDFLAGS_upper_add1_debug) -o $@ $^  

get_name_static_upper_add2_debug.axf: $(INPUTS_COMMON_LINK_upper_add2_debug) $(DEP_PROJ_LINK_upper_add2_debug)
	$(LD_upper_add2_debug) $(LDFLAGS_upper_add2_debug) -o $@ $^  

get_name_static_lower_add1_release.axf: $(INPUTS_COMMON_LINK_lower_add1_release) $(DEP_PROJ_LINK_lower_add1_release)
	$(LD_lower_add1_release) $(LDFLAGS_lower_add1_release) -o $@ $^  

get_name_static_lower_add2_release.axf: $(INPUTS_COMMON_LINK_lower_add2_release) $(DEP_PROJ_LINK_lower_add2_release)
	$(LD_lower_add2_release) $(LDFLAGS_lower_add2_release) -o $@ $^  

get_name_static_upper_add1_release.axf: $(INPUTS_COMMON_LINK_upper_add1_release) $(DEP_PROJ_LINK_upper_add1_release)
	$(LD_upper_add1_release) $(LDFLAGS_upper_add1_release) -o $@ $^  

get_name_static_upper_add2_release.axf: $(INPUTS_COMMON_LINK_upper_add2_release) $(DEP_PROJ_LINK_upper_add2_release)
	$(LD_upper_add2_release) $(LDFLAGS_upper_add2_release) -o $@ $^  

get_name_static_lower_add1_ti_simulate.axf: $(INPUTS_COMMON_LINK_lower_add1_ti_simulate) $(DEP_PROJ_LINK_lower_add1_ti_simulate)
	$(LD_lower_add1_ti_simulate) $(LDFLAGS_lower_add1_ti_simulate) -o $@ $^  

get_name_static_lower_add2_ti_simulate.axf: $(INPUTS_COMMON_LINK_lower_add2_ti_simulate) $(DEP_PROJ_LINK_lower_add2_ti_simulate)
	$(LD_lower_add2_ti_simulate) $(LDFLAGS_lower_add2_ti_simulate) -o $@ $^  

get_name_static_upper_add1_ti_simulate.axf: $(INPUTS_COMMON_LINK_upper_add1_ti_simulate) $(DEP_PROJ_LINK_upper_add1_ti_simulate)
	$(LD_upper_add1_ti_simulate) $(LDFLAGS_upper_add1_ti_simulate) -o $@ $^  

get_name_static_upper_add2_ti_simulate.axf: $(INPUTS_COMMON_LINK_upper_add2_ti_simulate) $(DEP_PROJ_LINK_upper_add2_ti_simulate)
	$(LD_upper_add2_ti_simulate) $(LDFLAGS_upper_add2_ti_simulate) -o $@ $^  

%.get_name_static_tisim_coffabi_c674_c6run_lower_add1_debug.o: %.c
	$(CC_lower_add1_debug) $(CFLAGS_lower_add1_debug) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_lower_add1_debug.d $(DEFINES_lower_add1_debug) $(INCLUDES_lower_add1_debug) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_lower_add1_release.o: %.c
	$(CC_lower_add1_release) $(CFLAGS_lower_add1_release) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_lower_add1_release.d $(DEFINES_lower_add1_release) $(INCLUDES_lower_add1_release) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_lower_add1_ti_simulate.o: %.c
	$(CC_lower_add1_ti_simulate) $(CFLAGS_lower_add1_ti_simulate) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_lower_add1_ti_simulate.d $(DEFINES_lower_add1_ti_simulate) $(INCLUDES_lower_add1_ti_simulate) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_lower_add2_debug.o: %.c
	$(CC_lower_add2_debug) $(CFLAGS_lower_add2_debug) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_lower_add2_debug.d $(DEFINES_lower_add2_debug) $(INCLUDES_lower_add2_debug) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_lower_add2_release.o: %.c
	$(CC_lower_add2_release) $(CFLAGS_lower_add2_release) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_lower_add2_release.d $(DEFINES_lower_add2_release) $(INCLUDES_lower_add2_release) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_lower_add2_ti_simulate.o: %.c
	$(CC_lower_add2_ti_simulate) $(CFLAGS_lower_add2_ti_simulate) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_lower_add2_ti_simulate.d $(DEFINES_lower_add2_ti_simulate) $(INCLUDES_lower_add2_ti_simulate) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_upper_add1_debug.o: %.c
	$(CC_upper_add1_debug) $(CFLAGS_upper_add1_debug) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_upper_add1_debug.d $(DEFINES_upper_add1_debug) $(INCLUDES_upper_add1_debug) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_upper_add1_release.o: %.c
	$(CC_upper_add1_release) $(CFLAGS_upper_add1_release) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_upper_add1_release.d $(DEFINES_upper_add1_release) $(INCLUDES_upper_add1_release) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_upper_add1_ti_simulate.o: %.c
	$(CC_upper_add1_ti_simulate) $(CFLAGS_upper_add1_ti_simulate) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_upper_add1_ti_simulate.d $(DEFINES_upper_add1_ti_simulate) $(INCLUDES_upper_add1_ti_simulate) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_upper_add2_debug.o: %.c
	$(CC_upper_add2_debug) $(CFLAGS_upper_add2_debug) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_upper_add2_debug.d $(DEFINES_upper_add2_debug) $(INCLUDES_upper_add2_debug) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_upper_add2_release.o: %.c
	$(CC_upper_add2_release) $(CFLAGS_upper_add2_release) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_upper_add2_release.d $(DEFINES_upper_add2_release) $(INCLUDES_upper_add2_release) -o$@ $<

%.get_name_static_tisim_coffabi_c674_c6run_upper_add2_ti_simulate.o: %.c
	$(CC_upper_add2_ti_simulate) $(CFLAGS_upper_add2_ti_simulate) --preproc_dependency=$*.get_name_static_tisim_coffabi_c674_c6run_upper_add2_ti_simulate.d $(DEFINES_upper_add2_ti_simulate) $(INCLUDES_upper_add2_ti_simulate) -o$@ $<

CLEAN_COMMON_COMPILE_lower_add1_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add1_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_lower_add1_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add1_release.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_lower_add1_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add1_ti_simulate.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_lower_add2_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add2_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_lower_add2_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add2_release.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_lower_add2_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_lower_add2_ti_simulate.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_upper_add1_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add1_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_upper_add1_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add1_release.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_upper_add1_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add1_ti_simulate.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_upper_add2_debug = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add2_debug.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_upper_add2_release = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add2_release.d,$(COMMON_FILES))
CLEAN_COMMON_COMPILE_upper_add2_ti_simulate = $(addsuffix .get_name_static_tisim_coffabi_c674_c6run_upper_add2_ti_simulate.d,$(COMMON_FILES))

cleandeps:
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add1_release)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add1_ti_simulate)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add2_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add2_release)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add2_ti_simulate)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add1_release)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add1_ti_simulate)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add2_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add2_release)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add2_ti_simulate)

clean: cleanself
	$(MAKE) -C $(BASE)example-2/make/libfoo_static/tisim_coffabi_c674_c6run cleanself

cleanself:
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add1_release)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add1_ti_simulate)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add2_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add2_release)
	$(RM) $(CLEAN_COMMON_COMPILE_lower_add2_ti_simulate)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add1_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add1_release)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add1_ti_simulate)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add2_debug)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add2_release)
	$(RM) $(CLEAN_COMMON_COMPILE_upper_add2_ti_simulate)
	$(RM) $(INPUTS_COMMON_LINK_lower_add1_debug)
	$(RM) $(INPUTS_COMMON_LINK_lower_add2_debug)
	$(RM) $(INPUTS_COMMON_LINK_upper_add1_debug)
	$(RM) $(INPUTS_COMMON_LINK_upper_add2_debug)
	$(RM) $(INPUTS_COMMON_LINK_lower_add1_release)
	$(RM) $(INPUTS_COMMON_LINK_lower_add2_release)
	$(RM) $(INPUTS_COMMON_LINK_upper_add1_release)
	$(RM) $(INPUTS_COMMON_LINK_upper_add2_release)
	$(RM) $(INPUTS_COMMON_LINK_lower_add1_ti_simulate)
	$(RM) $(INPUTS_COMMON_LINK_lower_add2_ti_simulate)
	$(RM) $(INPUTS_COMMON_LINK_upper_add1_ti_simulate)
	$(RM) $(INPUTS_COMMON_LINK_upper_add2_ti_simulate)
	$(RM) get_name_static_lower_add1_debug.axf
	$(RM) get_name_static_lower_add2_debug.axf
	$(RM) get_name_static_upper_add1_debug.axf
	$(RM) get_name_static_upper_add2_debug.axf
	$(RM) get_name_static_lower_add1_release.axf
	$(RM) get_name_static_lower_add2_release.axf
	$(RM) get_name_static_upper_add1_release.axf
	$(RM) get_name_static_upper_add2_release.axf
	$(RM) get_name_static_lower_add1_ti_simulate.axf
	$(RM) get_name_static_lower_add2_ti_simulate.axf
	$(RM) get_name_static_upper_add1_ti_simulate.axf
	$(RM) get_name_static_upper_add2_ti_simulate.axf

.PHONY: default FORCE clean cleandeps cleanself help

FORCE:

help:
	@echo "This makefile has the following targets:"
	@echo " get_name_static_lower_add1_debug.axf"
	@echo " get_name_static_lower_add2_debug.axf"
	@echo " get_name_static_upper_add1_debug.axf"
	@echo " get_name_static_upper_add2_debug.axf"
	@echo " get_name_static_lower_add1_release.axf"
	@echo " get_name_static_lower_add2_release.axf"
	@echo " get_name_static_upper_add1_release.axf"
	@echo " get_name_static_upper_add2_release.axf"
	@echo " get_name_static_lower_add1_ti_simulate.axf"
	@echo " get_name_static_lower_add2_ti_simulate.axf"
	@echo " get_name_static_upper_add1_ti_simulate.axf"
	@echo " get_name_static_upper_add2_ti_simulate.axf"
	@echo " default"
	@echo " clean"
	@echo " cleandeps"
	@echo " help"

include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_lower_add1_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_lower_add1_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_lower_add1_debug.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_lower_add1_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_lower_add1_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_lower_add1_release.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_lower_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_lower_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_lower_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_lower_add2_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_lower_add2_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_lower_add2_debug.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_lower_add2_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_lower_add2_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_lower_add2_release.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_lower_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_lower_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_lower_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_upper_add1_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_upper_add1_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_upper_add1_debug.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_upper_add1_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_upper_add1_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_upper_add1_release.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_upper_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_upper_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_upper_add1_ti_simulate.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_upper_add2_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_upper_add2_debug.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_upper_add2_debug.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_upper_add2_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_upper_add2_release.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_upper_add2_release.d)
include $(wildcard $(BASE)example-2/frontend/main.get_name_static_tisim_coffabi_c674_c6run_upper_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name.get_name_static_tisim_coffabi_c674_c6run_upper_add2_ti_simulate.d)
include $(wildcard $(BASE)example-2/src/get_name/get_name_raw.get_name_static_tisim_coffabi_c674_c6run_upper_add2_ti_simulate.d)

%.lib: FORCE
	$(MAKE) -C $(@D) $(@F)


