#-*-makefile-*-

BASE=../../../../
ARFLAGS_add1_arm_simulate = -rc
ARFLAGS_add1_debug = -rc
ARFLAGS_add1_release = -rc
ARFLAGS_add2_arm_simulate = -rc
ARFLAGS_add2_debug = -rc
ARFLAGS_add2_release = -rc
AR_add1_arm_simulate = armar
AR_add1_debug = armar
AR_add1_release = armar
AR_add2_arm_simulate = armar
AR_add2_debug = armar
AR_add2_release = armar
CCDEP_add1_arm_simulate = armcc
CCDEP_add1_debug = armcc
CCDEP_add1_release = armcc
CCDEP_add2_arm_simulate = armcc
CCDEP_add2_debug = armcc
CCDEP_add2_release = armcc
CC_add1_arm_simulate = armcc
CC_add1_debug = armcc
CC_add1_release = armcc
CC_add2_arm_simulate = armcc
CC_add2_debug = armcc
CC_add2_release = armcc
CFLAGS_add1_arm_simulate = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O3 -Otime --apcs=/interwork -c --c99
CFLAGS_add1_debug = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O0 --apcs=/interwork -c --c99
CFLAGS_add1_release = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -O3 -Otime --apcs=/interwork -c --c99
CFLAGS_add2_arm_simulate = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O3 -Otime --apcs=/interwork -c --c99
CFLAGS_add2_debug = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O0 --apcs=/interwork -c --c99
CFLAGS_add2_release = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -O3 -Otime --apcs=/interwork -c --c99
CXXFLAGS_add1_arm_simulate = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O3 -Otime --apcs=/interwork -c
CXXFLAGS_add1_debug = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O0 --apcs=/interwork -c
CXXFLAGS_add1_release = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -O3 -Otime --apcs=/interwork -c
CXXFLAGS_add2_arm_simulate = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O3 -Otime --apcs=/interwork -c
CXXFLAGS_add2_debug = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -g -O0 --apcs=/interwork -c
CXXFLAGS_add2_release = --cpu=Cortex-A9.no_neon --fpu=VFPv3_D16 --thumb -O3 -Otime --apcs=/interwork -c
CXX_add1_arm_simulate = armcc
CXX_add1_debug = armcc
CXX_add1_release = armcc
CXX_add2_arm_simulate = armcc
CXX_add2_debug = armcc
CXX_add2_release = armcc
DEFINES_add1_arm_simulate = -DADD_THIS=1 -DNDEBUG=1
DEFINES_add1_debug = -DADD_THIS=1
DEFINES_add1_release = -DADD_THIS=1 -DNDEBUG=1
DEFINES_add2_arm_simulate = -DADD_THIS=2 -DNDEBUG=1
DEFINES_add2_debug = -DADD_THIS=2
DEFINES_add2_release = -DADD_THIS=2 -DNDEBUG=1
INCLUDES_add1_arm_simulate = -I$(BASE).
INCLUDES_add1_debug = -I$(BASE).
INCLUDES_add1_release = -I$(BASE).
INCLUDES_add2_arm_simulate = -I$(BASE).
INCLUDES_add2_debug = -I$(BASE).
INCLUDES_add2_release = -I$(BASE).


INPUTS_ARCHIVE_add1_arm_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.o\
                                   $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.o\
                                   $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.o
INPUTS_ARCHIVE_add1_debug = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.o\
                            $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.o
INPUTS_ARCHIVE_add1_release = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.o\
                              $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.o
INPUTS_ARCHIVE_add2_arm_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.o\
                                   $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.o\
                                   $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.o
INPUTS_ARCHIVE_add2_debug = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.o\
                            $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.o
INPUTS_ARCHIVE_add2_release = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.o $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.o\
                              $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.o


default: libfoo_static_add1_arm_simulate.lib libfoo_static_add2_arm_simulate.lib libfoo_static_add1_debug.lib libfoo_static_add2_debug.lib libfoo_static_add1_release.lib libfoo_static_add2_release.lib

libfoo_static_add1_arm_simulate.lib: $(INPUTS_ARCHIVE_add1_arm_simulate)
	$(AR_add1_arm_simulate) $(ARFLAGS_add1_arm_simulate)   $@ $^

libfoo_static_add2_arm_simulate.lib: $(INPUTS_ARCHIVE_add2_arm_simulate)
	$(AR_add2_arm_simulate) $(ARFLAGS_add2_arm_simulate)   $@ $^

libfoo_static_add1_debug.lib: $(INPUTS_ARCHIVE_add1_debug)
	$(AR_add1_debug) $(ARFLAGS_add1_debug)   $@ $^

libfoo_static_add2_debug.lib: $(INPUTS_ARCHIVE_add2_debug)
	$(AR_add2_debug) $(ARFLAGS_add2_debug)   $@ $^

libfoo_static_add1_release.lib: $(INPUTS_ARCHIVE_add1_release)
	$(AR_add1_release) $(ARFLAGS_add1_release)   $@ $^

libfoo_static_add2_release.lib: $(INPUTS_ARCHIVE_add2_release)
	$(AR_add2_release) $(ARFLAGS_add2_release)   $@ $^

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.o: %.c
	$(CCDEP_add1_arm_simulate) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add1_arm_simulate) $(INCLUDES_add1_arm_simulate) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d $<
	$(CC_add1_arm_simulate) $(CFLAGS_add1_arm_simulate) $(DEFINES_add1_arm_simulate) $(INCLUDES_add1_arm_simulate) -o $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.o: %.cpp
	$(CCDEP_add1_arm_simulate) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add1_arm_simulate) $(INCLUDES_add1_arm_simulate) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d $<
	$(CXX_add1_arm_simulate) $(CXXFLAGS_add1_arm_simulate) $(DEFINES_add1_arm_simulate) $(INCLUDES_add1_arm_simulate) -o  $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.o: %.c
	$(CCDEP_add1_debug) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add1_debug) $(INCLUDES_add1_debug) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d $<
	$(CC_add1_debug) $(CFLAGS_add1_debug) $(DEFINES_add1_debug) $(INCLUDES_add1_debug) -o $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.o: %.cpp
	$(CCDEP_add1_debug) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add1_debug) $(INCLUDES_add1_debug) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d $<
	$(CXX_add1_debug) $(CXXFLAGS_add1_debug) $(DEFINES_add1_debug) $(INCLUDES_add1_debug) -o  $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.o: %.c
	$(CCDEP_add1_release) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add1_release) $(INCLUDES_add1_release) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d $<
	$(CC_add1_release) $(CFLAGS_add1_release) $(DEFINES_add1_release) $(INCLUDES_add1_release) -o $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.o: %.cpp
	$(CCDEP_add1_release) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add1_release) $(INCLUDES_add1_release) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d $<
	$(CXX_add1_release) $(CXXFLAGS_add1_release) $(DEFINES_add1_release) $(INCLUDES_add1_release) -o  $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.o: %.c
	$(CCDEP_add2_arm_simulate) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add2_arm_simulate) $(INCLUDES_add2_arm_simulate) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d $<
	$(CC_add2_arm_simulate) $(CFLAGS_add2_arm_simulate) $(DEFINES_add2_arm_simulate) $(INCLUDES_add2_arm_simulate) -o $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.o: %.cpp
	$(CCDEP_add2_arm_simulate) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add2_arm_simulate) $(INCLUDES_add2_arm_simulate) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d $<
	$(CXX_add2_arm_simulate) $(CXXFLAGS_add2_arm_simulate) $(DEFINES_add2_arm_simulate) $(INCLUDES_add2_arm_simulate) -o  $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.o: %.c
	$(CCDEP_add2_debug) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add2_debug) $(INCLUDES_add2_debug) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d $<
	$(CC_add2_debug) $(CFLAGS_add2_debug) $(DEFINES_add2_debug) $(INCLUDES_add2_debug) -o $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.o: %.cpp
	$(CCDEP_add2_debug) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add2_debug) $(INCLUDES_add2_debug) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d $<
	$(CXX_add2_debug) $(CXXFLAGS_add2_debug) $(DEFINES_add2_debug) $(INCLUDES_add2_debug) -o  $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.o: %.c
	$(CCDEP_add2_release) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add2_release) $(INCLUDES_add2_release) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d $<
	$(CC_add2_release) $(CFLAGS_add2_release) $(DEFINES_add2_release) $(INCLUDES_add2_release) -o $@ $<

%.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.o: %.cpp
	$(CCDEP_add2_release) --cpu=Cortex-A9.no_neon --mm $(DEFINES_add2_release) $(INCLUDES_add2_release) -o $@ > $*.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d $<
	$(CXX_add2_release) $(CXXFLAGS_add2_release) $(DEFINES_add2_release) $(INCLUDES_add2_release) -o  $@ $<

CLEAN_COMPILE_add1_arm_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d\
                                  $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d\
                                  $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d
CLEAN_COMPILE_add1_debug = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d
CLEAN_COMPILE_add1_release = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d\
                             $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d
CLEAN_COMPILE_add2_arm_simulate = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d\
                                  $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d\
                                  $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d
CLEAN_COMPILE_add2_debug = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d\
                           $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d
CLEAN_COMPILE_add2_release = $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d\
                             $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d

cleandeps:
	$(RM) $(CLEAN_COMPILE_add1_arm_simulate)
	$(RM) $(CLEAN_COMPILE_add1_debug)
	$(RM) $(CLEAN_COMPILE_add1_release)
	$(RM) $(CLEAN_COMPILE_add2_arm_simulate)
	$(RM) $(CLEAN_COMPILE_add2_debug)
	$(RM) $(CLEAN_COMPILE_add2_release)

clean: cleanself

cleanself:
	$(RM) $(CLEAN_COMPILE_add1_arm_simulate)
	$(RM) $(CLEAN_COMPILE_add1_debug)
	$(RM) $(CLEAN_COMPILE_add1_release)
	$(RM) $(CLEAN_COMPILE_add2_arm_simulate)
	$(RM) $(CLEAN_COMPILE_add2_debug)
	$(RM) $(CLEAN_COMPILE_add2_release)
	$(RM) $(INPUTS_ARCHIVE_add1_arm_simulate)
	$(RM) $(INPUTS_ARCHIVE_add2_arm_simulate)
	$(RM) $(INPUTS_ARCHIVE_add1_debug)
	$(RM) $(INPUTS_ARCHIVE_add2_debug)
	$(RM) $(INPUTS_ARCHIVE_add1_release)
	$(RM) $(INPUTS_ARCHIVE_add2_release)
	$(RM) libfoo_static_add1_arm_simulate.lib
	$(RM) libfoo_static_add2_arm_simulate.lib
	$(RM) libfoo_static_add1_debug.lib
	$(RM) libfoo_static_add2_debug.lib
	$(RM) libfoo_static_add1_release.lib
	$(RM) libfoo_static_add2_release.lib

.PHONY: default FORCE clean cleandeps cleanself help

FORCE:

help:
	@echo "This makefile has the following targets:"
	@echo " libfoo_static_add1_arm_simulate.lib"
	@echo " libfoo_static_add2_arm_simulate.lib"
	@echo " libfoo_static_add1_debug.lib"
	@echo " libfoo_static_add2_debug.lib"
	@echo " libfoo_static_add1_release.lib"
	@echo " libfoo_static_add2_release.lib"
	@echo " default"
	@echo " clean"
	@echo " cleandeps"
	@echo " help"

include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_arm_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add1_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_arm_simulate.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_debug.d)
include $(wildcard $(BASE)example-2/src/foo/foo.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_asm.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d)
include $(wildcard $(BASE)example-2/src/foo/foo_cpp.libfoo_static_rvbare_cortex_a9_vfp_t2_rvct_add2_release.d)


